ISL/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('loans/', include('loans.urls')),
    path('admin_panel/', include('admin_panel.urls')),
    path('', include('books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from . import views
from .views import book_list, book_detail, book_create, book_update, book_delete, author_delete


urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('book/', book_list, name='book_list'),
    path('catalog/', views.book_list_reader, name='book_list_reader'),
    path('book/<int:pk>/', book_detail, name='book_detail'),
    path('book/create/', book_create, name='book_create'),
    path('book/<int:pk>/update/', book_update, name='book_update'),
    path('book/<int:pk>/delete/', book_delete, name='book_delete'),
    path('book/deleted_books/', views.deleted_books, name='deleted_books'),
    path('book/restore_book/<int:pk>/', views.restore_book, name='restore_book'),
    path('genres/', views.GenreListView.as_view(), name='genre_list'),
    path('genres/add/', views.GenreCreateView.as_view(), name='genre_add'),
    path('genres/<int:pk>/edit/', views.GenreUpdateView.as_view(), name='genre_edit'),
    path('genres/<int:pk>/delete/', views.GenreDeleteView.as_view(), name='genre_delete'),
    path('deleted_genres/', views.deleted_genres, name='deleted_genres'),
    path('restore_genre/<int:pk>/', views.restore_genre, name='restore_genre'),
    path('authors/', views.AuthorListView.as_view(), name='author_list'),
    path('authors/add/', views.AuthorCreateView.as_view(), name='author_add'),
    path('authors/<int:pk>/edit/', views.AuthorUpdateView.as_view(), name='author_edit'),
    path('authors/<int:pk>/delete/', author_delete, name='author_delete'),
    path('deleted_authors/', views.deleted_authors, name='deleted_authors'),
    path('restore_author/<int:pk>/', views.restore_author, name='restore_author'),
    path('editions/', views.EditionListView.as_view(), name='edition_list'),
    path('editions/add/', views.EditionCreateView.as_view(), name='edition_add'),
    path('editions/<int:pk>/edit/', views.EditionUpdateView.as_view(), name='edition_edit'),
    path('editions/<int:pk>/delete/', views.EditionDeleteView.as_view(), name='edition_delete'),
    path('deleted_editions/', views.DeletedEditionListView.as_view(), name='deleted_editions'),
    path('restore_edition/<int:pk>/', views.restore_edition, name='restore_edition'),
    path('<int:pk>/', views.book_detail, name='book_detail'),
    path('copies/', views.book_copy_list, name='book_copy_list'),
    path('copies/create/', views.book_copy_create, name='book_copy_create'),
    path('copies/<int:pk>/edit/', views.book_copy_edit, name='book_copy_edit'),
    path('copies/<int:pk>/delete/', views.book_copy_delete, name='book_copy_delete'),
    path('deleted_bookcopies/', views.DeletedBookCopyListView.as_view(), name='deleted_bookcopies'),
    path('restore_bookcopy/<int:pk>/', views.book_copy_restore, name='book_copy_restore'),
]

books/models.py
from django.db import models


class Edition(models.Model):
    edition_name = models.CharField(max_length=255)
    deleted_flag = models.BooleanField(default=False)

    def __str__(self):
        return self.edition_name


class Author(models.Model):
    author_name = models.CharField(max_length=255)
    deleted_flag = models.BooleanField(default=False)

    def __str__(self):
        return self.author_name


class Genre(models.Model):
    genre_name = models.CharField(max_length=255)
    deleted_flag = models.BooleanField(default=False)

    def __str__(self):
        return self.genre_name


class Book(models.Model):
    edition = models.ForeignKey(Edition, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    publication_year = models.IntegerField(null=True, blank=True)
    cover_image = models.ImageField(upload_to='', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    deleted_flag = models.BooleanField(default=False)
    authors = models.ManyToManyField(Author, through='BooksAuthors')
    genres = models.ManyToManyField(Genre, through='BooksGenres')

    def __str__(self):
        return self.title


class CopiesStatus(models.Model):
    status = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.status


class BookCopy(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE)
    book_number = models.IntegerField(unique=True)
    status = models.ForeignKey(CopiesStatus, on_delete=models.CASCADE)  # Связь с CopiesStatus
    deleted_flag = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.book.title} - Copy {self.book_number} ({self.status})"


class BooksAuthors(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)


class BooksGenres(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

books/views.py
from datetime import date
from django.core.paginator import Paginator
from admin_panel.views import log_action
from django.shortcuts import render, redirect, get_object_or_404
from loans.models import Reservation
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from .forms import *
from .models import *


def book_list(request):
    genre_filter = request.GET.get('genre')
    author_filter = request.GET.get('author')
    title_filter = request.GET.get('title')

    books = Book.objects.filter(deleted_flag=False)

    if genre_filter:
        books = books.filter(genre__genre_name__icontains=genre_filter)
    if author_filter:
        books = books.filter(author__author_name__icontains=author_filter)
    if title_filter:
        books = books.filter(title__icontains=title_filter)

    genres = Genre.objects.filter(deleted_flag=False)
    authors = Author.objects.filter(deleted_flag=False)

    return render(request, 'books/book_list.html', {
        'books': books,
        'genres': genres,
        'authors': authors,
        'selected_genre': genre_filter,
        'selected_author': author_filter,
        'selected_title': title_filter
    })


def book_detail(request, pk):
    book = get_object_or_404(Book.objects.prefetch_related('authors', 'genres'), pk=pk)

    user_has_active_reservation = False
    is_librarian = False

    if request.user.is_authenticated:
        is_librarian = request.user.role.role_name == 'Библиотекарь'

        active_reservation_exists = Reservation.objects.filter(
            reader=request.user,
            copy__book=book,
            status__status_name__in=['Создана', 'Активна'],
            reservation_end_date__gte=date.today()
        ).exists()

        if active_reservation_exists:
            user_has_active_reservation = True

        closed_reservation_exists = Reservation.objects.filter(
            reader=request.user,
            copy__book=book,
            status__status_name__in=['Закрыта', 'Истекла', 'Отменена']
        ).exists()

        if not active_reservation_exists and closed_reservation_exists:
            user_has_active_reservation = False

    return render(
        request,
        template_name='books/book_detail.html',
        context={
            'book': book,
            'user_has_active_reservation': user_has_active_reservation,
            'is_librarian': is_librarian,
        }
    )


def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save()

            authors = form.cleaned_data['authors']
            for author in authors:
                BooksAuthors.objects.get_or_create(book=book, author=author)

            genres = form.cleaned_data['genres']
            for genre in genres:
                BooksGenres.objects.get_or_create(book=book, genre=genre)

            log_action(request.user, 'CREATE', 'Book', book.id, f"Создана книга {book.title}")
            return redirect('book_list')
    else:
        form = BookForm()
    return render(request, 'books/book_form.html', {'form': form})


def book_update(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect('book_list')
    else:
        form = BookForm(instance=book)
    return render(request, 'books/book_form.html', {'form': form})


def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    book.deleted_flag = True
    book.save()
    return redirect('book_list')


class GenreListView(ListView):
    model = Genre
    template_name = 'genres/genre_list.html'
    context_object_name = 'genres'

    def get_queryset(self):
        return Genre.objects.filter(deleted_flag=False)


class GenreCreateView(CreateView):
    model = Genre
    form_class = GenreForm
    template_name = 'genres/genre_form.html'
    success_url = reverse_lazy('genre_list')

    def form_valid(self, form):
        response = super().form_valid(form)
        log_action(self.request.user, 'CREATE', 'Genre', self.object.id, f"Создан жанр {self.object.genre_name}")
        return response


class GenreUpdateView(UpdateView):
    model = Genre
    form_class = GenreForm
    template_name = 'genres/genre_form.html'
    success_url = reverse_lazy('genre_list')

    def form_valid(self, form):
        response = super().form_valid(form)
        log_action(self.request.user, 'UPDATE', 'Genre', self.object.id, f"Обновлен жанр {self.object.genre_name}")
        return response


class AuthorListView(ListView):
    model = Author
    template_name = 'authors/author_list.html'
    context_object_name = 'authors'

    def get_queryset(self):
        return Author.objects.filter(deleted_flag=False)


class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorForm
    template_name = 'authors/author_form.html'
    success_url = reverse_lazy('author_list')


class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AuthorForm
    template_name = 'authors/author_form.html'
    success_url = reverse_lazy('author_list')


class EditionListView(ListView):
    model = Edition
    template_name = 'editions/edition_list.html'
    context_object_name = 'editions'

    def get_queryset(self):
        return Edition.objects.filter(deleted_flag=False)


class EditionCreateView(CreateView):
    model = Edition
    form_class = EditionForm
    template_name = 'editions/edition_form.html'
    success_url = reverse_lazy('edition_list')


class EditionUpdateView(UpdateView):
    model = Edition
    form_class = EditionForm
    template_name = 'editions/edition_form.html'
    success_url = reverse_lazy('edition_list')


class GenreDeleteView(View):
    def get(self, request, pk):
        genre = get_object_or_404(Genre, pk=pk)
        genre.deleted_flag = True
        genre.save()
        return redirect(reverse_lazy('genre_list'))


def author_delete(request, pk):
    author = get_object_or_404(Author, pk=pk)
    author.deleted_flag = True
    author.save()
    log_action(request.user, 'DELETE', 'Author', author.id, f"Автор {author.author_name} был удален")
    return redirect(reverse_lazy('author_list'))


class EditionDeleteView(View):
    def get(self, request, pk):
        edition = get_object_or_404(Edition, pk=pk)
        edition.deleted_flag = True
        edition.save()
        log_action(request.user, 'DELETE', 'Edition', edition.id, f"Издание {edition.edition_name} было удалено")
        return redirect(reverse_lazy('edition_list'))


class DeletedEditionListView(ListView):
    model = Edition
    template_name = 'editions/deleted_editions.html'
    context_object_name = 'deleted_editions'

    def get_queryset(self):
        return Edition.objects.filter(deleted_flag=True)


def book_list_reader(request):
    query = request.GET.get('q', '')
    author_filter = request.GET.get('author', '')
    genre_filter = request.GET.get('genre', '')

    books = Book.objects.filter(deleted_flag=False)

    if query:
        books = books.filter(title__icontains=query)
    if author_filter:
        books = books.filter(authors__author_name__icontains=author_filter)
    if genre_filter:
        books = books.filter(genres__genre_name__icontains=genre_filter)

    books = books.distinct()

    paginator = Paginator(books, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    authors = Author.objects.filter(deleted_flag=False)
    genres = Genre.objects.filter(deleted_flag=False)

    return render(request, 'books/book_list_reader.html', {
        'page_obj': page_obj,
        'query': query,
        'author_filter': author_filter,
        'genre_filter': genre_filter,
        'authors': authors,
        'genres': genres,
    })


def book_copy_list(request):
    copies = BookCopy.objects.filter(deleted_flag=False)
    return render(request, 'book_copies/book_copy_list.html', {'copies': copies})


class BookCopyListView(ListView):
    model = BookCopy
    template_name = 'book_copies/book_copy_list.html'
    context_object_name = 'book_copies'

    def get_queryset(self):
        return BookCopy.objects.filter(deleted_flag=False)


def book_copy_create(request):
    if request.method == 'POST':
        form = BookCopyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book_copy_list')
    else:
        form = BookCopyForm()
    return render(request, 'book_copies/book_copy_form.html', {'form': form})


def book_copy_edit(request, pk):
    copy = get_object_or_404(BookCopy, pk=pk)
    if request.method == 'POST':
        form = BookCopyForm(request.POST, instance=copy)
        if form.is_valid():
            form.save()
            return redirect('book_copy_list')
    else:
        form = BookCopyForm(instance=copy)
    return render(request, 'book_copies/book_copy_form.html', {'form': form})


def book_copy_delete(request, pk):
    book_copy = get_object_or_404(BookCopy, pk=pk)
    book_copy.deleted_flag = True
    book_copy.save()
    log_action(request.user, 'DELETE', 'BookCopy', book_copy.id, f"Копия книги {book_copy.book.title} была удалена")
    return redirect('book_copy_list')


class DeletedBookCopyListView(ListView):
    model = BookCopy
    template_name = 'book_copies/deleted_book_copies.html'
    context_object_name = 'deleted_book_copies'

    def get_queryset(self):
        return BookCopy.objects.filter(deleted_flag=True)


def book_copy_restore(request, pk):
    book_copy = get_object_or_404(BookCopy, pk=pk, deleted_flag=True)
    book_copy.deleted_flag = False
    book_copy.save()
    log_action(request.user, 'RESTORE', 'BookCopy', book_copy.id, f"Копия книги {book_copy.book.title} была восстановлена")

books/templates/books/book_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>{{ book.title }}</h1>
    <div class="row mb-3">
        <div class="col-md-4">
            <img src="{{ book.cover_image.url }}" alt="Обложка книги" class="img-fluid">
        </div>
        <div class="col-md-8">
            <p><strong>Издание:</strong> {{ book.edition.edition_name }}</p>
            <p><strong>Год публикации:</strong> {{ book.publication_year }}</p>
            <p><strong>Авторы:</strong> {{ book.authors.all|join:", " }}</p>
            <p><strong>Жанры:</strong> {{ book.genres.all|join:", " }}</p>
            <p><strong>Описание:</strong> {{ book.description }}</p>

            {% if not is_librarian %}
                <div class="mb-3">
                    {% if user.is_authenticated %}
                        {% if user_has_active_reservation %}
                            <button class="btn btn-secondary mb-2" style="width: 200px;">Уже забронировано</button>
                        {% else %}
                            <form action="{% url 'book_reserve' book.pk %}" method="post" class="mb-2">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success" style="width: 200px;">Забронировать</button>
                            </form>
                        {% endif %}
                    {% else %}
                        <p class="text-danger">Авторизуйтесь, чтобы забронировать книгу.</p>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

books/templates/books/book_form.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-4">Добавить книгу</h1>
<form method="post" enctype="multipart/form-data" class="row g-4">
    {% csrf_token %}

    <div class="col-12">
        <h4 class="fw-bold">Основная информация</h4>
        <hr>
    </div>
    <div class="col-md-6">
        <label for="id_title" class="form-label fw-bold">Название книги</label>
        <input type="text" name="title" id="id_title" class="form-control" value="{{ form.instance.title }}">
    </div>
    <div class="col-md-6">
    {{ form.edition.label_tag|safe }}<br>
    {{ form.edition }}
</div>


    <div class="col-12">
        <h4 class="fw-bold mt-4">Авторы и Жанры</h4>
        <hr>
    </div>
    <div class="col-md-6">
        <label class="form-label fw-bold d-block">Авторы</label>
        <div>
            {% for author in form.authors %}
                <div class="form-check">
                    {{ author.tag }} {{ author.choice_label }}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-6">
        <label class="form-label fw-bold d-block">Жанры</label>
        <div>
            {% for genre in form.genres %}
                <div class="form-check">
                    {{ genre.tag }} {{ genre.choice_label }}
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="col-12">
        <h4 class="fw-bold mt-4">Дополнительная информация</h4>
        <hr>
    </div>
    <div class="col-md-6">
        <label for="id_publication_year" class="form-label fw-bold">Год публикации</label>
        {{ form.publication_year }}
    </div>

    <div class="col-md-6">
        <label for="id_cover_image" class="form-label fw-bold">Обложка книги</label>
        {{ form.cover_image }}
    </div>

    <div class="col-12">
        <label for="id_description" class="form-label fw-bold">Описание</label>
        {{ form.description }}
    </div>

    <div class="col-12">
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </div>
</form>
{% endblock %}

books/templates/books/book_list.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>Список книг</h1>
    <div>
        <a href="{% url 'book_create' %}" class="btn btn-success">Добавить книгу</a>
        <a href="{% url 'deleted_books' %}" class="btn btn-warning">Восстановить удалённые книги</a>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Название</th>
            <th>Издание</th>
            <th>Год публикации</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
            <tr>
                <td><a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a></td>
                <td>{{ book.edition.edition_name }}</td>
                <td>{{ book.publication_year }}</td>
                <td>
                    <a href="{% url 'book_update' book.pk %}" class="btn btn-primary btn-sm">Редактировать</a>
                    <a href="{% url 'book_delete' book.pk %}" class="btn btn-danger btn-sm" onclick="return confirm('Вы уверены, что хотите удалить эту книгу?');">Удалить</a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4">Нет книг в списке.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

books/templates/books/book_list_reader.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Каталог книг</h1>

<form method="get" class="mb-4">
    <div class="row">
        <div class="col-md-4">
            <input type="text" name="q" class="form-control" placeholder="Поиск по названию" value="{{ query }}">
        </div>
        <div class="col-md-3">
            <select name="author" class="form-control">
                <option value="">Все авторы</option>
                {% for author in authors %}
                    <option value="{{ author.author_name }}" {% if author_filter == author.author_name %}selected{% endif %}>{{ author.author_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-3">
            <select name="genre" class="form-control">
                <option value="">Все жанры</option>
                {% for genre in genres %}
                    <option value="{{ genre.genre_name }}" {% if genre_filter == genre.genre_name %}selected{% endif %}>{{ genre.genre_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-2">
            <button type="submit" class="btn btn-primary w-100">Фильтр</button>
        </div>
    </div>
</form>

<div class="row">
    {% for book in page_obj %}
        <div class="col-md-2 col-sm-4 mb-3">
            <div class="card h-100" style="width: 100%; max-width: 150px;">
                {% if book.cover_image %}
                     <img src="{{ book.cover_image.url }}" class="card-img-top" alt="{{ book.title }}" style="height: 200px; object-fit: cover;">
                {% else %}
                    <img src="{% static 'default_cover.jpg' %}" class="card-img-top" alt="Обложка отсутствует" style="height: 200px; object-fit: cover;">
                {% endif %}
                <div class="card-body d-flex flex-column justify-content-between p-2">
                    <h6 class="card-title book-title text-center" style="font-size: 0.9rem;">{{ book.title }}</h6>
                    <a href="{% url 'book_detail' book.pk %}" class="btn btn-primary btn-sm mt-auto w-100">Подробнее</a>
                </div>
            </div>
        </div>
    {% empty %}
        <p>Нет книг, соответствующих вашему запросу.</p>
    {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1{% if query %}&q={{ query }}{% endif %}{% if author_filter %}&author={{ author_filter }}{% endif %}{% if genre_filter %}&genre={{ genre_filter }}{% endif %}">Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}{% if author_filter %}&author={{ author_filter }}{% endif %}{% if genre_filter %}&genre={{ genre_filter }}{% endif %}">Назад</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}{% if author_filter %}&author={{ author_filter }}{% endif %}{% if genre_filter %}&genre={{ genre_filter }}{% endif %}">Вперед</a>
            <a href="?page={{ page_obj.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}{% if author_filter %}&author={{ author_filter }}{% endif %}{% if genre_filter %}&genre={{ genre_filter }}{% endif %}">Последняя</a>
        {% endif %}
    </span>
</div>
{% endblock %}

books/templates/books/deleted_books.html
{% extends 'base.html' %}

{% block content %}
<h1>Удаленные книги</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Название</th>
            <th>Издание</th>
            <th>Год публикации</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{{ book.edition.edition_name }}</td>
                <td>{{ book.publication_year }}</td>
                <td>
                    <a href="{% url 'restore_book' book.pk %}" class="btn btn-success btn-sm">Восстановить</a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4">Нет удаленных книг.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'book_list' %}" class="btn btn-secondary">Назад к списку книг</a>
{% endblock %}